# Configuration Constants
RANDOM_STATE: 42
TARGET_VARIABLE: "price"
MLFLOW_CALLBACK_METRIC_NAME: "cv_mape"

APPLY_SCALE_TRANSFORM: False
APPLY_PCA_IMG_TRANSFORM: False
APPLY_UMAP_IMG_TRANSFORM: False

# feature selection
N_ESTIMATORS: 200
RFE_STEP_SIZE: 10
N_PCA_COMPONENTS: 0.8
N_UMAP_COMPONENTS: 50
INCLUDE_LOCATION_FEATURES: True

MODEL_PREFIX: "model__"

column_definitions:
  target_variable_name: "price"
  district_column_name: "district"
  outlier_column_name: "outlier"

data_paths:
  train_test_data: "data"
  train_test_img: "data" 