experiment_version: "v6"

feature_sets:
  - "rfecv_all_nfeat_158_pca_count_loc.json"
  - "rfecv_base_nfeat_56_nonpca_count_loc.json"
  - "rfecv_all_nfeat_158_umap_count_loc.json"
  - "rfecv_base_poi_pano_nfeat_158_nonpca_count_loc.json"


models_to_run:
  - "LightGBM"

feature_sets_dir: "feature_sets"
optuna_dir: "optuna_studies"
artifact_path: "models_and_artifacts"

target_variable: "price"

# Data filtering options
data_filtering:
  filter_by_has_img: true

cv_folds: 5
tuning_cv_folds: 5

# Optuna hyperparameter tuning settings
optuna:
  n_trials: 100
  scoring_metric: 
    - "mape"
  direction: "minimize"
  db_file: "tuning.db"

# MLflow settings
mlflow:
  tracking_uri: "./mlruns"
  experiment_name_prefix: "RE price predictor" 