feature_sets:
  - "rfecv_all_nfeat_81_nonpca_count.json"
  - "rfecv_all_nfeat_44_pca_scaled_count.json"

models_to_run:
  - "LightGBM"
  - "XGBoost"
  - "RandomForest"


feature_sets_dir: "feature_sets"
optuna_dir: "optuna_studies"
artifact_path: "models_and_artifacts"

target_variable: "price"

cv_folds: 5

# Optuna hyperparameter tuning settings
optuna:
  n_trials: 100
  scoring_metric: 
    - "mape"
    - "rmse"
  direction: "minimize"
  db_file: "tuning.db"

# MLflow settings
mlflow:
  tracking_uri: "./mlruns"
  experiment_name_prefix: "RE price predictor" 