experiment_version: "v1"

feature_sets:
  - "rfecv_base_nfeat_117_nonpca_count_loc.json"
  - "rfecv_base_poi_pano_nfeat_160_nonpca_count_loc.json"
  - "rfecv_all_nfeat_152_nonpca_count_loc.json"
  - "comb_all_nfeat_201_pca_count_loc.json"



models_to_run:
  - "XGBoost"
  - "RandomForest"

feature_sets_dir: "feature_sets"
optuna_dir: "optuna_studies"
artifact_path: "models_and_artifacts"

target_variable: "price"

cv_folds: 5

# Optuna hyperparameter tuning settings
optuna:
  n_trials: 100
  scoring_metric: 
    - "mape"
  direction: "minimize"
  db_file: "tuning.db"

# MLflow settings
mlflow:
  tracking_uri: "./mlruns"
  experiment_name_prefix: "RE price predictor" 